import { promises as FS } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'

import { Repository } from '../../models/repository'
import { git } from './core'

const DiffTreeTempPrefix = 'github-desktop-diff-tree-'

export const DiffTreeAgentInstructions = `Generate a diff tree that can be loaded directly into GitHub Desktop.

The text you return will be copied to the system clipboard. GitHub Desktop reads that clipboard text, validates the entire patch with Git, and then applies it to the current working tree.

Return a standard Git-compatible patch that is valid input for "git apply".

Formatting requirements:
- Output only the raw patch text.
- Do not use Markdown code fences.
- Do not include explanations, comments, shell commands, JSON, XML, or any other wrapper.
- All paths must be relative to the repository root.
- Never use absolute paths or paths containing "../".
- Each changed file should use the standard "diff --git a/<path> b/<path>" header.
- Text modifications must use standard "---", "+++", and "@@" unified-diff hunks.
- New files must use standard Git new-file patch syntax, including "new file mode" and "--- /dev/null".
- Deleted files must use standard Git deleted-file patch syntax, including "deleted file mode" and "+++ /dev/null".
- Renames should use standard Git rename metadata such as "similarity index", "rename from", and "rename to".
- Preserve exact whitespace in context, removed, and added lines.
- Include file mode changes using standard Git patch metadata when needed.
- Binary files may only use a valid "GIT binary patch" generated by Git. Never invent or approximate binary patch payloads.
- The patch must apply cleanly to the current working tree without relying on three-way merge behavior.
- The clipboard text must be acceptable to "git apply --check --binary --whitespace=nowarn" before it is applied.

Return only the patch text.`

async function withTemporaryDirectory<T>(
  operation: (directory: string) => Promise<T>
): Promise<T> {
  const directory = await FS.mkdtemp(join(tmpdir(), DiffTreeTempPrefix))

  try {
    return await operation(directory)
  } finally {
    await FS.rm(directory, { recursive: true, force: true })
  }
}

async function repositoryHasHead(repository: Repository): Promise<boolean> {
  const result = await git(
    ['rev-parse', '--verify', 'HEAD'],
    repository.path,
    'check for HEAD before creating diff tree',
    { successExitCodes: new Set([0, 128]) }
  )

  return result.exitCode === 0
}

/**
 * Create a Git-compatible patch containing all current working-directory
 * changes without modifying the repository's real index.
 */
export async function getWorkingDirectoryDiffTree(
  repository: Repository
): Promise<string> {
  return withTemporaryDirectory(async directory => {
    const temporaryIndex = join(directory, 'index')
    const env = { GIT_INDEX_FILE: temporaryIndex }
    const hasHead = await repositoryHasHead(repository)

    if (hasHead) {
      await git(
        ['read-tree', 'HEAD'],
        repository.path,
        'initialize temporary diff tree index',
        { env }
      )
    } else {
      await git(
        ['read-tree', '--empty'],
        repository.path,
        'initialize empty temporary diff tree index',
        { env }
      )
    }

    await git(
      ['add', '-A', '--', '.'],
      repository.path,
      'populate temporary diff tree index',
      { env }
    )

    const args = [
      'diff',
      '--cached',
      '--binary',
      '--full-index',
      '--no-color',
      '--no-ext-diff',
      '--find-renames',
    ]

    if (hasHead) {
      args.push('HEAD')
    }

    args.push('--')

    const result = await git(
      args,
      repository.path,
      'create working directory diff tree',
      { env }
    )

    return result.stdout
  })
}

/**
 * Validate and apply a Git-compatible diff tree to the working directory.
 */
export async function applyDiffTree(
  repository: Repository,
  diffTree: string
): Promise<void> {
  if (diffTree.trim().length === 0) {
    throw new Error('The system clipboard does not contain a diff tree.')
  }

  await withTemporaryDirectory(async directory => {
    const patchPath = join(directory, 'diff-tree.patch')
    await FS.writeFile(patchPath, diffTree, 'utf8')

    const applyArgs = ['--binary', '--whitespace=nowarn', '--', patchPath]

    await git(
      ['apply', '--check', ...applyArgs],
      repository.path,
      'validate clipboard diff tree'
    )

    await git(
      ['apply', ...applyArgs],
      repository.path,
      'apply clipboard diff tree'
    )
  })
}
